name: Generate Snake Animation

on:
  # Jalan otomatis setiap jam 12 malam
  schedule:
    - cron: "0 0 * * *" 
  # Bisa dijalankan manual
  workflow_dispatch:
  
  # Jalan setiap kali ada push ke branch master/main
  push:
    branches:
    - master
    - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Langkah 1: Checkout kode repository
      - name: Checkout
        uses: actions/checkout@v3

      # Langkah 2: Generate file snake (pacman) dari grafik kontribusi
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg?palette=github-dark

      # Langkah 3: Push file gambar ke branch 'output'
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
